import { supportsWebGL } from './generic';

const SettingsConfig = [
  {
    type: 'section',
    label: '设置',
    name: 'sectionSettingsCollapsed',
    default: false,
  },
  {
    name: 'advancedSettings',
    label: '高级',
    type: 'checkbox',
    default: false,
  },
  {
    name: 'enabled',
    label: '启用',
    type: 'checkbox',
    default: true,
    defaultKey: 'G',
  },
  {
    type: 'section',
    label: '画质',
    name: 'sectionQualityPerformanceCollapsed',
    default: false,
    advanced: true,
  },
  {
    name: 'webGL',
    label: 'WebGL 渲染器（功耗更低）',
    description: '更改后将重新加载网页',
    type: 'checkbox',
    default: true,
    advanced: true,
  },
  {
    name: 'resolution',
    label: '分辨率',
    type: 'list',
    default: 100,
    unit: '%',
    valuePoints: (() => {
      const points = [6.25];
      while (points[points.length - 1] < 400) {
        points.push(points[points.length - 1] * 2);
      }
      return points;
    })(),
    manualinput: false,
    advanced: true,
  },
  {
    name: 'framerateLimit',
    label: '限制帧率（每秒）',
    type: 'list',
    default: 60,
    min: 0,
    max: 60,
    step: 1,
    advanced: true,
  },
  {
    name: 'frameSync',
    label: '同步方式',
    questionMark: {
      title:
        '控制同步氛围灯帧与视频帧时消耗的性能。\n\n解码帧率：CPU 和 GPU 占用最低，但可能出现丢帧和延迟。\n\n显示帧率：CPU 和 GPU 占用最高。\n\n视频帧率：使用浏览器视频帧回调，尽量保持同步。',
    },
    type: 'list',
    default: 2,
    min: 0,
    max: 2,
    step: 1,
    snapPoints: [
      { value: 0, label: '解码' },
      { value: 1, label: '显示' },
      { value: 2, label: '视频' },
    ],
    manualinput: false,
    advanced: true,
    experimental: true,
  },
  {
    name: 'prioritizePageLoadSpeed',
    label: '优先网页加载速度',
    description: '网页加载完成后再启动氛围灯',
    type: 'checkbox',
    default: true,
    advanced: true,
  },
  {
    name: 'energySaver',
    label: '静态视频节能',
    description: '画面静止时自动降低帧率',
    type: 'checkbox',
    default: false,
    advanced: true,
  },
  {
    type: 'section',
    label: '视频',
    name: 'sectionVideoResizingCollapsed',
    default: false,
    advanced: true,
  },
  {
    name: 'videoScale.SMALL',
    label: '普通布局尺寸',
    type: 'list',
    default: 100,
    min: 25,
    max: 200,
    step: 0.1,
    new: true,
    advanced: true,
  },
  {
    name: 'videoScale.THEATER',
    label: '宽屏布局尺寸',
    type: 'list',
    default: 100,
    min: 25,
    max: 200,
    step: 0.1,
    new: true,
    advanced: true,
  },
  {
    name: 'videoScale.FULLSCREEN',
    label: '全屏布局尺寸',
    type: 'list',
    default: 100,
    min: 25,
    max: 200,
    step: 0.1,
    new: true,
    advanced: true,
  },
  {
    name: 'videoShadowSize',
    label: '阴影大小',
    type: 'list',
    default: 0,
    min: 0,
    max: 100,
    step: 0.1,
    advanced: true,
  },
  {
    name: 'videoShadowOpacity',
    label: '阴影不透明度',
    type: 'list',
    default: 50,
    min: 0,
    max: 100,
    step: 0.1,
    advanced: true,
  },
  {
    name: 'videoDebandingStrength',
    label: '去色带（噪点）',
    questionMark: {
      title:
        '点击了解去色带（噪点/抖动）的更多信息。\n提示：将“画质 > 去色带优化目标”设为“OLED”，可在 OLED 显示器上保留纯黑。',
      href: 'https://www.lifewire.com/what-is-dithering-4686105',
    },
    type: 'list',
    default: 0,
    min: 0,
    max: 100,
    step: 1,
    advanced: true,
  },
  {
    type: 'section',
    label: '移除黑边',
    name: 'sectionHorizontalBarsCollapsed',
    default: true,
    advanced: true,
  },
  {
    name: 'detectHorizontalBarSizeEnabled',
    label: '移除上下黑边',
    description: '占用：CPU',
    type: 'checkbox',
    default: false,
    defaultKey: 'B',
    advanced: true,
  },
  {
    name: 'detectVerticalBarSizeEnabled',
    label: '移除左右黑边',
    description: '占用：CPU',
    type: 'checkbox',
    default: false,
    defaultKey: 'V',
    advanced: true,
  },
  {
    name: 'detectColoredHorizontalBarSizeEnabled',
    label: '检测彩色边框',
    type: 'checkbox',
    default: false,
    advanced: true,
  },
  {
    name: 'detectHorizontalBarSizeOffsetPercentage',
    label: '检测偏移',
    type: 'list',
    default: 0,
    min: -5,
    max: 5,
    step: 0.1,
    advanced: true,
  },
  {
    name: 'barSizeDetectionAverageHistorySize',
    label: '检测帧数平均',
    questionMark: {
      title:
        '用于计算平均黑边大小的视频帧数。\n帧数越少检测越快，但误判也会增多。',
    },
    type: 'list',
    default: 4,
    min: 1,
    max: 30,
    step: 1,
    advanced: true,
  },
  {
    name: 'barSizeDetectionAllowedElementsPercentage',
    label: '检测确定性阈值',
    questionMark: {
      title:
        '10% 时只移除明显的黑边。\n提高百分比后可移除包含部分元素的边框。\n继续提高可能裁剪到画面中央。',
    },
    type: 'list',
    default: 20,
    min: 10,
    max: 90,
    step: 10,
    advanced: true,
  },
  {
    name: 'barSizeDetectionAllowedUnevenBarsPercentage',
    label: '检测不均匀阈值',
    questionMark: {
      title:
        '百分比越高，越容易检测到上下或左右宽度不一致的黑边。\n过高也会把规则物体误判为黑边。',
    },
    type: 'list',
    default: 10,
    min: 1,
    max: 50,
    step: 1,
    advanced: true,
    new: true,
  },
  {
    name: 'horizontalBarsClipPercentage',
    label: '上下黑边大小',
    type: 'list',
    default: 0,
    min: 0,
    max: 40,
    step: 0.1,
    snapPoints: [
      { value: 8.7, label: 8 },
      { value: 12.3, label: 12, flip: true },
      { value: 13.5, label: 13 },
    ],
    advanced: true,
  },
  {
    name: 'verticalBarsClipPercentage',
    label: '左右黑边大小',
    type: 'list',
    default: 0,
    min: 0,
    max: 40,
    step: 0.1,
    advanced: true,
  },
  {
    name: 'horizontalBarsClipPercentageReset',
    label: '下个视频重置黑边',
    type: 'checkbox',
    default: true,
    advanced: true,
  },
  {
    name: 'detectVideoFillScaleEnabled',
    label: '用视频填充已移除黑边',
    type: 'checkbox',
    default: false,
    defaultKey: 'H',
    advanced: true,
  },
  {
    type: 'section',
    label: '滤镜',
    name: 'sectionImageAdjustmentCollapsed',
    default: false,
  },
  { name: 'brightness', label: '亮度', type: 'list', default: 100, min: 0, max: 200, step: 1 },
  { name: 'contrast', label: '对比度', type: 'list', default: 100, min: 0, max: 200, step: 1, advanced: true },
  { name: 'vibrance', label: '色彩', type: 'list', default: 100, min: 0, max: 200, step: 0.1, advanced: true },
  { name: 'saturation', label: '饱和度', type: 'list', default: 100, min: 0, max: 200, step: 1, advanced: true },
  {
    type: 'section',
    label: 'HDR 滤镜',
    name: 'sectionHdrImageAdjustmentCollapsed',
    default: false,
    hdr: true,
  },
  { name: 'hdrBrightness', label: '亮度', type: 'list', default: 100, min: 0, max: 200, step: 1, hdr: true },
  { name: 'hdrContrast', label: '对比度', type: 'list', default: 100, min: 0, max: 200, step: 1, hdr: true },
  { name: 'hdrSaturation', label: '饱和度', type: 'list', default: 100, min: 0, max: 200, step: 1, hdr: true },
  {
    type: 'section',
    label: '方向',
    name: 'sectionDirectionsCollapsed',
    default: false,
    advanced: true,
  },
  { name: 'directionTopEnabled', label: '顶部', type: 'checkbox', default: true, advanced: true },
  { name: 'directionRightEnabled', label: '右侧', type: 'checkbox', default: true, advanced: true },
  { name: 'directionBottomEnabled', label: '底部', type: 'checkbox', default: true, advanced: true },
  { name: 'directionLeftEnabled', label: '左侧', type: 'checkbox', default: true, advanced: true },
  {
    type: 'section',
    label: '氛围灯',
    name: 'sectionAmbientlightCollapsed',
    default: false,
  },
  {
    name: 'blur2',
    label: '光晕柔和度',
    description: '占用：GPU 显存',
    type: 'list',
    default: 30,
    min: 0,
    max: 100,
    step: 0.1,
  },
  {
    name: 'edge',
    label: '边缘大小',
    description: '将模糊设为 0% 可更清楚地查看变化',
    type: 'list',
    default: 12,
    min: 2,
    max: 50,
    step: 0.1,
    advanced: true,
  },
  {
    name: 'spread',
    label: '光晕范围',
    description: '占用：GPU',
    type: 'list',
    default: 17,
    min: 0,
    max: 400,
    step: 0.1,
  },
  {
    name: 'spreadFadeStart',
    label: '扩散衰减起点',
    type: 'list',
    default: 15,
    min: -50,
    max: 100,
    step: 0.1,
    advanced: true,
  },
  {
    name: 'spreadFadeCurve',
    label: '扩散衰减曲线',
    description: '将模糊设为 0% 可更清楚地查看变化',
    type: 'list',
    default: 35,
    min: 1,
    max: 100,
    step: 1,
    advanced: true,
  },
  {
    name: 'debandingStrength',
    label: '去色带（噪点）',
    questionMark: {
      title: '点击了解噪点/抖动的更多信息。',
      href: 'https://www.lifewire.com/what-is-dithering-4686105',
    },
    type: 'list',
    default: 0,
    min: 0,
    max: 100,
    step: 1,
    advanced: true,
  },
  {
    name: 'debandingBlendMode',
    label: '去色带优化目标',
    type: 'list',
    default: 0,
    min: 0,
    max: 1,
    step: 1,
    snapPoints: [
      { value: 0, label: 'LCD（普通）' },
      { value: 1, label: 'OLED（叠加）' },
    ],
    manualinput: false,
    advanced: true,
    new: true,
  },
  {
    name: 'frameFading',
    label: '淡入时长',
    description: '占用：GPU 显存',
    type: 'list',
    default: 0,
    min: 0,
    max: 21.2,
    step: 0.02,
    manualinput: false,
    advanced: true,
  },
  {
    name: 'flickerReduction',
    label: '闪烁抑制',
    type: 'list',
    default: 0,
    min: 0,
    max: 100,
    step: 1,
    manualinput: false,
    advanced: true,
  },
  {
    name: 'frameBlending',
    label: '平滑运动（帧混合）',
    description: '占用：GPU',
    type: 'checkbox',
    default: false,
    advanced: true,
  },
  {
    name: 'frameBlendingSmoothness',
    label: '平滑强度',
    type: 'list',
    default: 80,
    min: 0,
    max: 100,
    step: 1,
    advanced: true,
  },
  {
    name: 'fixedPosition',
    label: '固定位置',
    description: '忽略页面滚动位置',
    type: 'checkbox',
    default: false,
    advanced: true,
  },
  {
    type: 'section',
    label: '性能与显示',
    name: 'sectionPerformanceDisplayCollapsed',
    default: false,
    advanced: true,
  },
  {
    name: 'showFPS',
    label: '显示 FPS',
    description: '在播放器左上角显示氛围灯帧率',
    type: 'checkbox',
    default: false,
    advanced: true,
  },
  {
    name: 'showFrametimes',
    label: '显示帧时间',
    description: '显示氛围灯各阶段耗时',
    type: 'checkbox',
    default: false,
    advanced: true,
  },
  {
    name: 'showResolutions',
    label: '显示渲染分辨率',
    description: '显示投影器与缓冲区尺寸',
    type: 'checkbox',
    default: false,
    advanced: true,
  },
  {
    name: 'showBarDetectionStats',
    label: '显示黑边检测统计',
    description: '显示黑边检测曲线与结果',
    type: 'checkbox',
    default: false,
    advanced: true,
  },
  {
    name: 'hideScrollbar',
    label: '隐藏滚动条',
    description: '氛围灯开启时隐藏页面滚动条',
    type: 'checkbox',
    default: false,
    advanced: true,
  },
  {
    name: 'layoutPerformanceImprovements',
    label: '布局性能优化',
    description: '降低评论与推荐列表渲染开销',
    type: 'checkbox',
    default: true,
    advanced: true,
  },
  {
    type: 'section',
    label: '布局',
    name: 'sectionViewsCollapsed',
    default: false,
    advanced: true,
  },
  { name: 'enableInNormal', label: '普通布局', type: 'checkbox', default: true, advanced: true },
  { name: 'enableInWide', label: '宽屏布局', type: 'checkbox', default: true, advanced: true },
  { name: 'enableInWebFullscreen', label: '网页全屏', type: 'checkbox', default: true, advanced: true },
  { name: 'enableInFullscreen', label: '原生全屏', type: 'checkbox', default: true, advanced: true },
];

export const WebGLOnlySettings = [
  'resolution',
  'vibrance',
  'frameFading',
  'flickerReduction',
  'fixedPosition',
];

let prepared = false;
export const prepareSettingsConfigOnce = () => {
  if (prepared) return;

  const settingsToRemove = [];
  for (const setting of SettingsConfig) {
    if (!supportsWebGL()) {
      if (WebGLOnlySettings.includes(setting.name)) settingsToRemove.push(setting.name);
      if (setting.name === 'webGL') {
        setting.default = false;
        setting.disabled = '你的浏览器已禁用 WebGL。';
      }
    }

    if (setting.name === 'frameSync' && !HTMLVideoElement.prototype.requestVideoFrameCallback) {
      setting.max = 1;
      if (setting.default > 1) setting.default = 0;
    }
  }

  for (const settingName of settingsToRemove) {
    const index = SettingsConfig.findIndex((setting) => setting.name === settingName);
    if (index !== -1) SettingsConfig.splice(index, 1);
  }

  prepared = true;
};

export default SettingsConfig;
